services:
  backend:
    build:
      context: ./back-end
      dockerfile: dockerfile
    volumes:
      - ./back-end/upload/documents:/upload/documents
      - ./back-end/migration:/app/migration
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./back-end/config/.env.dev
    environment:
      - PORT=8000
      - HOST=localhost
      - DB_HOST=${DB_HOST}
      - DB_USER=user
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONNECTION=tcp
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      dockerfile: dockerfile
    ports:
      - "3000:5173"
    restart: unless-stopped