services:
  backend:
    build:
      context: ./back-end
      dockerfile: dockerfile
    volumes:
      - ./back-end/upload/documents:/upload/documents
      - ./back-end/migration:/app/migration
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
      - ./back-end/config/.env.prod
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      dockerfile: dockerfile
    ports:
      - "3000:5173"
    restart: unless-stopped

networks:
  default:
    name: resolve_now_default